Retire Old Weather: Whaling
zooniverse/retirement pull request #9
Opened 2019-04-05 19:33 UTC by wgranger

Creates folder and adds content for Old Weather: Whaling retirement.

2019-04-05 19:59 UTC, srallen requested changes
Looks like some files maybe used on the other static retirement pages got copied into this folder. The other project images in `/img` as well as the pngs for the apple and microsoft tiles and the xml file can be removed.

Also let's set the background color for the body to what the jumbotron section is using, `#eee` so it doesn't look like there's missing content.

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/index.html
> +        <link rel="apple-touch-icon" href="apple-touch-icon.png">
This is just a placeholder for the web. This can be removed.

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/index.html
> +          <a class="navbar-brand" href="#">Archived Zooniverse Project: Old Weather: Whaling</a>
Maybe just make this a span

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/index.html
> +          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
Remove this. On mobile it's showing a hamburger menu that doesn't work.

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/index.html
> +        <div id="navbar" class="navbar-collapse collapse">
Also remove this.

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/index.html
> +    <div class="container">
Remove this.

2019-04-05 19:59 UTC, srallen commented on OldWeatherWhaling/css/main.css
> +img.similar {
The styles starting on this line and down aren't being used and can be removed.

2019-04-05 20:34 UTC, wgranger commented
Thanks for the keen eye on the review. I also added some css to make the page responsive at mobile widths.

2019-04-08 09:04 UTC, srallen approved these changes

2019-04-09 14:16 UTC, wgranger commented
Are we waiting on anything else for this, or can it be merged?

2019-04-09 17:04 UTC, merged